// http://voteview.com/party3.htm
var PARTIES = {
    "214": "Non-Partisan and Republican", 
    "215": "War Democrat", 
    "212": "United Republican", 
    "213": "Progressive Republican", 
    "603": "Ind. Whig", 
    "6000": "Crawford Federalist", 
    "555": "Jackson", 
    "337": "Anti-Monopoly Democrat", 
    "310": "American", 
    "331": "Ind. Republican", 
    "333": "Ind. Republican-Democrat", 
    "29": "Whig", 
    "9999": "Unknown", 
    "114": "Readjuster", 
    "117": "Readjuster Democrat", 
    "4000": "Anti-Administration", 
    "403": "Law and Order", 
    "110": "Popular Sovereignty Democrat", 
    "112": "Conservative", 
    "336": "Anti-Monopolist", 
    "119": "United Democrat", 
    "118": "Tariff for Revenue Democrat", 
    "25": "National Republican", 
    "26": "Anti Masonic", 
    "1111": "Liberty", 
    "8888": "Adams-Clay Republican", 
    "22": "Adams", 
    "46": "States Rights", 
    "44": "Nullifier", 
    "6666": "Crawford Republican", 
    "43": "Calhoun Nullifier", 
    "40": "Anti-Democrat and States Rights", 
    "41": "Anti-Jackson Democrat", 
    "1": "Federalist", 
    "347": "Prohibitionist", 
    "326": "National Greenbacker", 
    "341": "People's", 
    "401": "Fusionist", 
    "301": "Free Soil Democrat", 
    "9": "Jefferson Republican", 
    "340": "Populist", 
    "328": "Independent", 
    "329": "Ind. Democrat", 
    "402": "Liberal", 
    "308": "Free Soil American and Democrat", 
    "200": "Republican", 
    "203": "Unconditional Unionist", 
    "202": "Union Conservative", 
    "522": "American Labor", 
    "206": "Unionist", 
    "300": "Free Soil", 
    "208": "Liberal Republican", 
    "302": "Free Soil Whig", 
    "1116": "Conservative Republican", 
    "304": "Anti-Slavery", 
    "1275": "Anti-Jackson", 
    "380": "Socialist", 
    "108": "Anti-Lecompton Democrat", 
    "4444": "Union", 
    "1346": "Jackson Republican", 
    "9000": "Unknown", 
    "103": "Democrat and Anti-Mason", 
    "100": "Democrat", 
    "101": "Jackson Democrat", 
    "8000": "Adams-Clay Federalist", 
    "104": "Van Buren Democrat", 
    "105": "Conservative Democrat", 
    "11": "Jefferson Democrat", 
    "10": "Anti-Federalist", 
    "13": "Democrat-Republican", 
    "3333": "Opposition", 
    "48": "States Rights Whig", 
    "5000": "Pro-Administration", 
    "1061": "Emancipationist", 
    "1060": "Silver", 
    "37": "Constitutional Unionist", 
    "7777": "Crawford Republican", 
    "34": "Whig and Democrat", 
    "537": "Farmer-Labor", 
    "356": "Union Labor", 
    "355": "Union", 
    "354": "Silver Republican", 
    "353": "Ind. Silver Republican", 
    "370": "Progressive", 
    "7000": "Jackson Federalist"
}
